language: node_js
node_js:
- '9.11'

cache:
  directories:
    - "node_modules"

script:
  - yarn build  

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  target-branch: master
  on:
    branch: master