language: node_js
node_js:
- '12.1'

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn build  

deploy:
  provider: pages
  local_dir: /public
  github-token: $GITHUB_TOKEN
  committer-from-gh: true
  skip-cleanup: true
  keep-history: true
  target-branch: master
  on:
    branch: master